create table if not exists groups
(
    id    bigint generated by default as identity,
    title varchar not null,
    constraint groups_pk
        primary key (id)
);

create table if not exists users
(
    id    bigint generated by default as identity,
    name  varchar(50) not null,
    email varchar(120),
    password varchar(50),
    last_viewed_group_id bigint,
    constraint users_id_unique unique (id),
    constraint users_email_unique unique (email),
    constraint users_last_viewed_group_id_fk
        foreign key (last_viewed_group_id) references groups (id)
            on update cascade
);

create table if not exists users_groups
(
    user_id     bigint      not null,
    group_id    bigint      not null,
    status      varchar(10) not null,
    constraint users_groups_pk
        primary key (user_id, group_id),
    constraint users_groups_user_id_fk
        foreign key (user_id) references users (id)
            on update cascade,
    constraint users_groups_group_id_fk
        foreign key (group_id) references groups (id)
            on update cascade,
    constraint unique_user_group
        unique (user_id, group_id)
);

create table if not exists bills
(
    id         bigint generated by default as identity,
    type       varchar(15) not null,
    added_by   bigint  not null,
    title      varchar(50) not null,
    amount     integer not null,
    note       varchar (250),
    date       date not null,
    added_on   timestamp without time zone not null,
    constraint bills_pk
        primary key (id),
    constraint bills_added_by_fk
        foreign key (added_by) references users (id)
);

create table if not exists transactions
(
    id           bigint generated by default as identity,
    group_id     bigint  not null,
    bill_id      bigint  not null,
    user_id      bigint  not null,
    amount       integer not null,
    tr_type      varchar (15) not null,
    constraint transactions_pk
        primary key (id),
    constraint transactions_user_id_fk
        foreign key (user_id) references users (id),
    constraint transactions_group_id_fk
        foreign key (group_id) references groups (id),
    constraint transactions_bill_id_fk
        foreign key (bill_id) references bills (id)
);
